abbr f "code ~/.config/fish"
abbr l "ls -lhS"
abbr cls "clear"
abbr gs "git status"
abbr gco "git checkout"
abbr gcb "git checkout -b"
abbr gcm "git checkout master"
abbr pull "git pull"
abbr push "git push"
abbr gl 'git log --pretty=format:"%C(yellow)%h %C(green)%cn %n%C(cyan)%ad %C(reset)(%ar)%n%s%n" --graph'
abbr gwch "git whatchanged -p --abbrev-commit --pretty=medium"
abbr listen "lsof -n -i | grep LISTEN"
abbr ds "docker rm (docker ps -aq) -f"
abbr dps "docker ps -a"
abbr dim "docker images"
abbr dra "docker rmi (docker images -q)"
abbr drm "docker rmi (docker images -q --filter "dangling=true")"
